#!/bin/bash

rm -rf /tmp/DiscordUpate/
echo Preparation...
mkdir -p /tmp/DiscordUpdate/
cd /tmp/DiscordUpdate
echo Downloading the new version...
wget -O discord.tar.gz "https://discord.com/api/download?platform=linux&format=tar.gz"
echo Extracting...
tar -xvzf discord.tar.gz
echo Installing...
cp -r Discord/* ~/Documents/Discord
echo Cleanup...
rm -rf /tmp/DiscordUpate/
echo Done!
